{{- $fullName := include "dev-helm.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $branch := .Values.branch}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "dev-helm.name" . }}
    helm.sh/chart: {{ include "dev-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ $branch }}.{{ .Values.repo }}-dev.aca-aws.s.uw.edu
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.repo }}-dev-{{ .Values.branch }}
              servicePort: http
